### ISSUE TITLE
Server error 500

### ISSUE THREAD

**Issue by Bongsakorn** [keedio/kafka-hue#43] opened 2015-03-28 05:59 UTC
Hello, 

I got error "Server error 500" when access to Kafka app. In error.log, I got this
```
[28/Mar/2015 12:55:34 +0700] base         ERROR    Internal Server Error: /kafka
Traceback (most recent call last):
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/middleware/common.py", line 68, in process_request
    urlresolvers.is_valid_path("%s/" % request.path_info, urlconf)):
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/urlresolvers.py", line 300, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/urlresolvers.py", line 300, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/urlresolvers.py", line 209, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/urlresolvers.py", line 216, in callback
    self._callback = get_callable(self._callback_str)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/utils/functional.py", line 27, in wrapper
    result = func(*args)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/core/urlresolvers.py", line 92, in get_callable
    lookup_view = getattr(import_module(mod_name), func_name)
  File "/usr/lib/hue/build/env/lib/python2.6/site-packages/Django-1.4.5-py2.6.egg/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/lib/hue/apps/kafka/src/kafka/views.py", line 20, in <module>
    from kazoo.client import KazooClient, KazooState
ImportError: No module named kazoo.client
```
and in hue.ini I set like this
```hue.ini
[kafka]

 [[clusters]]

  [[[default]]]
    # Zookeeper ensemble. Comma separated list of Host/Port.
    # e.g. localhost:2181,localhost:2182,localhost:2183
    zk_host_ports=zk-beta1:2181,zk-beta2:2181

    # The URL of the REST contrib service (required for znode browsing)
    zk_rest_url=http://localhost:9998

    # Path to brokers info in Zookeeper Znode hierarchy
    brokers_path=/brokers/ids

    # Path to consumers info in Zookeeper Znode hierarchy
    consumers_path=/consumers
```

**Comment by danieltardon** [comment] 2015-03-31 08:02
Hi @Bongsakorn,

It seems that you have not installed the Kazoo library. 

> ImportError: No module named kazoo.client

You have the installation instructions at the Readme. 

Next week we will release a new version of Kafka-HUE in which the installation of this library is not required. If you can't wait to that, install the Kazoo library.

$ sudo $HUE_HOME/build/env/bin/python $HUE_HOME/build/env/bin/pip install zope.interface
$ sudo $HUE_HOME/build/env/bin/python $HUE_HOME/build/env/bin/pip install kazoo

**Comment by Bongsakorn** [comment] 2015-03-31 09:28
Thank you for your response.

I already installed follow your instruction. I think, perhaps, the problem is in step 

sudo ../tools/app_reg/app_reg.py --install kafka --relative-paths

It doesn't create table kafka. However, I will waiting for your new release.

**Comment by danieltardon** [comment] 2015-03-31 09:34
I don't think so. The log says that the problem is with the Kazoo library, that it seems to be missing. 

Try reinstalling the Kafka-HUE app (if you missed the Kazoo library the first time) or making a syncdb.

**Comment by danieltardon** [comment] 2015-04-07 14:47
Hi @Bongsakorn,

did you fix your problem? Could I close the issue?

Thanks

**Comment by Bongsakorn** [comment] 2015-04-08 11:51
Hi,

 I don't try yet, I'm very busy. You don't update new release yet, right? Ok, You can close issue if I will notice you again when I try to re-install again.

**Comment by danieltardon** [comment] 2015-04-08 12:04
Hi, 

You can access to a new relaese 2.0. It's available since yesterday. 

I'll close the issue and if you have more problems (even with the 1.X version) feel free to reopen it or open a new one. 

Thanks

**Closed by danieltardon** 2015-04-08 12:04 UTC
